name: dr_alshaal
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+8

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^2.0.6
  shared_preferences: ^2.0.16
  dio: ^5.7.0
  internet_connection_checker: ^2.0.0
  persistent_bottom_nav_bar: any
  retrofit: ^4.4.1
  json_serializable: ^6.5.4
  get: ^4.6.5
  flutter_spinkit: ^5.1.0
  fancy_shimmer_image: ^2.0.2
  dropdown_button2: ^2.3.9
  firebase_messaging: ^15.1.2
  firebase_core: ^3.5.0
  flutter_local_notifications: ^17.2.2
  package_info_plus: ^8.0.2
  device_info: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter_html: ^3.0.0-beta.2
  calendar_date_picker2: ^1.1.7
  url_launcher: ^6.1.10
  youtube_player_flutter: ^9.0.3
  video_player: ^2.6.1
  webview_flutter: ^4.2.0
  permission_handler: ^11.3.1
  share_plus: ^10.0.2
  file_picker: ^8.1.2
  path_provider: ^2.0.13
  uni_links: ^0.5.1
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  flutter_downloader: ^1.10.4
  open_filex: ^4.3.2
  text_scroll: ^0.2.0
  flutter_zoom_drawer: ^3.0.4+1
  tutorial_coach_mark: ^1.2.8
  chewie: ^1.5.0
  flutter_pdfview: ^1.2.7
  flutter_cached_pdfview: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.2.1
  build_runner: ^2.3.3
  isar_generator: ^3.0.5
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/




  fonts:
    - family: Sukar
      fonts:
        - asset: assets/fonts/Sukar_Bold.ttf

